#Following this doc instruction https://proandroiddev.com/android-lint-workflow-using-github-actions-327b56cb6535

name: Run Android Lint
run-name: Running Android Lint
on: [push]

jobs:

  android-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Make gradlew executable
        run: chmod +x ./gradlew


      - name: Run Lint
        run: ./gradlew lint